export const KEY_CODES = {
    ESCAPE:  27,
    SPACE:  32,
    COMMA:  44,
    NINE:  57,
}

export const CLASSES = {
    VS_APP: 'VS-App',
    VS_APP_HEADER: 'VS-App-header',
    VS_CALENDAR_CONTAINER: 'VS-CalendarContainer',
    VS_DATEPICKER_CONTAINER: 'VS-DatepickerContainer',
    VS_SHAPE_ROUNDED_FILL_BUTTON: 'VS-shape-rounded-fill-with-button',
    VS_SHAPE_ROUNDED_FILL_FOR_MONTH: 'VS-shape-rounded-fill-for-month',
    VS_SHAPE_ROUNDED_FILL_FOR_QUARTER: 'VS-shape-rounded-fill-for-quarter',
    VS_SHAPE_ROUNDED_FILL_FOR_YEAR: 'VS-shape-rounded-fill-for-year',
    VS_SHAPE_ROUNDED_FILL: 'VS-shape-rounded-fill',
    VS_MODAL: 'VS-modal',
    VS_ACTIVE: 'VS-Active',
    VS_YEAR: 'VS-Year',
    VS_MRG_T5: 'VS-MrgT5',
    VS_TEXT_RIGHT: 'VS-TextRight',
    VS_TEXT_CENTER: 'VS-TextCenter',
    VS_TEXT_LEFT: 'VS-TextLeft',
    VS_PULL_RIGHT: 'VS-PullRight',
    VS_PULL_LEFT: 'VS-PullLeft',
    VS_REG_UPPER_CASE: 'VS-Regular-UPPER-Case',
    VS_MED_UPPER_CASE: 'VS-Medium-UPPER-Case',
    VS_INVALID_INPUT: 'VS-Invalid-Input',
    VS_INVALID_TEXT: 'VS-InvalidText',
    VS_INPUT_BORDER: 'VS-Input-Border',
    VS_CALENDAR_INPUT: 'VS-Calendar-Input',
    VS_DATE_ROW: 'VS-DateRow',
    VS_DATE_ROW_FLEX: 'VS-DateRowFlex',
    VS_CAL_DAY: 'VS-CalDay',
    VS_CALENDAR_DAY: 'VS-CalendarDay',
    VS_CALENDAR_WEEK: 'VS-CalendarWeek',
    VS_CALENDAR_MONTH: 'VS-CalendarMonth',
    VS_MONTH_NAME: 'VS-MonthName',
    VS_MONTH_QUARTER: 'VS-MonthQuarter',
    VS_DAY: 'VS-Day',
    VS_DAY_START: 'VS-DayStart',
    VS_NEXT_PREV_DAY: 'VS-NextPrevDay',
    VS_INDIVATOR: 'VS-indicator',
    VS_ICON: 'VS-Icon',
    VS_DISABLED_ICON: 'VS-DisabledIcon',
    VS_INPUT_ICON: 'VS-Input-Icon',
    VS_CLOSE_ICON: 'VS-CloseIcon',
    VS_FILTER_ICON: 'VS-FilterIcon',
    VS_DISABLED_DAY: 'VS-DisabledDay',
    VS_DISABLED: 'VS-Disabled',
    VS_SHAPE: 'VS-Shape',
    VS_TEXT_DARK: 'VS-TextDark',
    VS_SELECT_BUTTON: 'VS-SelectButton',
    VS_CLEAR_BUTTON: 'VS-ClearButton',
    VS_CALENDAR_BUTTON: 'VS-CalendarButtons',
}